### ISSUE TITLE
exclude() and append() glob support

### ISSUE THREAD

**Issue by oojacoboo** [DarkGhostHunter/Preloader#3]
It'd be nice if we use use the glob syntax for `exclude` and `append` methods to decrease verbosity and get some wildcard support.

Additionally, it'd be nice to know what the generator looks for with the array values (updated docs).  Is it a relational file path, a simple string match, etc.

**Comment by DarkGhostHunter** [comment]
Does glob returns full paths? Because if I add glob support, or basically modify those two methods to use glob, then they should also get the full path of each file returned by glob using `realpath()`. And this function doesn't like files that do not exist.

I could put `excludeGlob()` and `appendGlob()` for less verbosity, since the advantage of using glob is very clear and It could help making the usage less difficult to read, but it will have to map the array using `realpath()` nonetheless.

```php
Preloader::make()->excludeGlob('Sources/*.php');
```

**Comment by oojacoboo** [comment]
I believe that it does return full paths and I would try not to add another method for this when they can be used together.

**Comment by DarkGhostHunter** [comment]
Added glob support in #5 .
