### ISSUE TITLE
'touch' throws an error if used on file that is not yours or unwritable

### ISSUE THREAD

**Issue by infostreams** [DarkGhostHunter/Preloader#48]
Specifically, the way you use `touch` in this line

https://github.com/DarkGhostHunter/Preloader/blob/8ddec1f01afba57f5a474a90b40fa362f00cfd9e/src/PreloaderCompiler.php#L97

is buggy. It can (and does) result in problems such as the one described here: https://github.com/composer/composer/issues/4070. 

I tried to rewrite your code here and submit a pull request, but I honestly don't understand what the code is trying to achieve. Are you trying to create a new file and then return the path? What happens if the file already exists? What happens if it cannot create the file? I think it returns the path of the file it couldn't create, but I don't see how that makes sense. Unfortunately the comment there didn't help me much.

I get a warning in my Sentry logs regularly because of this, I'm sure it's the same for other people. I think the code here needs cleaning up, but I don't know what you're trying to achieve so I couldn't do it for you. Sorry!

**Comment by DarkGhostHunter** [comment]
I think I fixed in https://github.com/DarkGhostHunter/Preloader/commit/a5c15377111dc7f4c7bee6333474b1218ef0ce3f.

The main idea of that code is to get the REAL PATH of the output file, before creating it. 

Now it checks if it exists, and if not, it will create a dummy file, get the real path, and then delete it.
