### ISSUE TITLE
 PHP Fatal error

### ISSUE THREAD

**Issue by hello-yunshu** [DarkGhostHunter/Preloader#6]
Uncaught TypeError: Typed property DarkGhostHunter\Preloader\PreloaderLister::$opcache must be unknown or null, DarkGhostHunter\Preloader\Opcache used in **\Composer\vendor\darkghosthunter\preloader\src\PreloaderLister.php:49

I have no idea what happend. 

php-7.4.0-ts;
Windows Apache with php_mod.

**Comment by DarkGhostHunter** [comment]
I neither do. For what I can read, PHP says the `$opcache` variable in the `PreloaderLister` class must be unknown or null. That is totally untrue, since [it's declared as an Opcache instance](https://github.com/DarkGhostHunter/Preloader/blob/master/src/PreloaderLister.php#L40).

The only part of the code that touches that is when you use `make()`, since [it reuses the same Opcache class instance](https://github.com/DarkGhostHunter/Preloader/blob/master/src/Preloader.php#L175).

Can you run tests in your machine and check if any of them doesn't pass? If they do, then it's something else in your system.

**Comment by paniy** [comment]
This problem seems to be solved in PHP 7.4.1. Upgraded PHP 7.4.1, everything is OK.

**Comment by hello-yunshu** [comment]
Finally, I found out why. I set opcache.file_cache. If I clear the local cache of opache and run it again, there will be no error.
